"""Add balance to subscriber

Revision ID: 2e96aac4a409
Revises: d6c94e13f5e8
Create Date: 2021-12-05 10:46:06.902852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e96aac4a409'
down_revision = 'd6c94e13f5e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('balance', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'balance')
    # ### end Alembic commands ###
