"""Create courses

Revision ID: 47e6d8f34a55
Revises: f43ebc2e3e38
Create Date: 2021-11-27 18:26:11.461936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e6d8f34a55'
down_revision = 'f43ebc2e3e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('subscription_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_code'], ['subscription.code'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_course_course_id'), 'course', ['course_id'], unique=False)
    op.drop_index('ix_subscription_code', table_name='subscription')
    op.create_index(op.f('ix_subscription_code'), 'subscription', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_code'), table_name='subscription')
    op.create_index('ix_subscription_code', 'subscription', ['code'], unique=False)
    op.drop_index(op.f('ix_course_course_id'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
