"""Create courses

Revision ID: 4e2224554fdb
Revises: f43ebc2e3e38
Create Date: 2021-11-27 08:56:21.826062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2224554fdb'
down_revision = 'f43ebc2e3e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('owner_id', sa.String(), nullable=False))
    op.add_column('course', sa.Column('subscription_code', sa.String(), nullable=True))
    op.drop_constraint('course_subscription_id_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'subscription', ['subscription_code'], ['code'])
    op.drop_column('course', 'subscription_id')
    op.drop_index('ix_subscription_code', table_name='subscription')
    op.create_index(op.f('ix_subscription_code'), 'subscription', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_code'), table_name='subscription')
    op.create_index('ix_subscription_code', 'subscription', ['code'], unique=False)
    op.add_column('course', sa.Column('subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_subscription_id_fkey', 'course', 'subscription', ['subscription_id'], ['code'])
    op.drop_column('course', 'subscription_code')
    op.drop_column('course', 'owner_id')
    # ### end Alembic commands ###
