"""Make subscription code not nullable

Revision ID: 657305fd9ed1
Revises: 4e2224554fdb
Create Date: 2021-11-27 09:03:40.478128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657305fd9ed1'
down_revision = '4e2224554fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'subscription_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'subscription_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
