"""create information to process payments on SubscriberSuscription

Revision ID: 6ad2c9e10a1a
Revises: c6f0d20fc1d7
Create Date: 2021-12-19 10:27:04.585781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad2c9e10a1a'
down_revision = 'c6f0d20fc1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber_suscription', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('subscriber_suscription', sa.Column('price', sa.Numeric(precision=21, scale=18), nullable=True))
    op.add_column('subscriber_suscription', sa.Column('payment_due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber_suscription', 'payment_due_date')
    op.drop_column('subscriber_suscription', 'price')
    op.drop_column('subscriber_suscription', 'payment_status')
    # ### end Alembic commands ###
