"""Create Course Students

Revision ID: 908d33aff67d
Revises: 344a331e0558
Create Date: 2021-12-19 18:19:42.733958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '908d33aff67d'
down_revision = '344a331e0558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_student',
    sa.Column('subscriber_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=21, scale=18), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('payment_due_date', sa.DateTime(), nullable=False),
    sa.Column('payment_collected_date', sa.DateTime(), nullable=True),
    sa.CheckConstraint('payment_due_date > created_date', name='subscriber_suscription_payment_due_date_check'),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscriber.subscriber_id'], ),
    sa.PrimaryKeyConstraint('subscriber_id', 'course_id')
    )
    op.alter_column('subscriber_suscription', 'price',
               existing_type=sa.NUMERIC(precision=21, scale=18),
               nullable=False)
    op.drop_column('subscriber_suscription', 'payment_status')
    op.drop_column('subscriber_suscription', 'payment_due_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber_suscription', sa.Column('payment_due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('subscriber_suscription', sa.Column('payment_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('subscriber_suscription', 'price',
               existing_type=sa.NUMERIC(precision=21, scale=18),
               nullable=True)
    op.drop_table('course_student')
    # ### end Alembic commands ###
