"""Relationship between Student and subscription

Revision ID: a6fa29e20a5c
Revises: 908d33aff67d
Create Date: 2021-12-20 19:21:14.019936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fa29e20a5c'
down_revision = '908d33aff67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_student', sa.Column('subscriber_suscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_student', 'subscriber_suscription', ['subscriber_suscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_student', type_='foreignkey')
    op.drop_column('course_student', 'subscriber_suscription_id')
    # ### end Alembic commands ###
