"""Add price and course_limit

Revision ID: c2f14af701f9
Revises: 47e6d8f34a55
Create Date: 2021-11-29 23:03:47.963947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import table, column, String, Integer, Numeric, orm

from app.db.models import Subscription

revision = 'c2f14af701f9'
down_revision = '47e6d8f34a55'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('price', sa.Numeric(precision=9, scale=2), nullable=True))
    op.add_column('subscription', sa.Column('course_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    for subscription in session.query(Subscription):
        if subscription.code == "FREE":
            subscription.price = 0
            subscription.course_limit = 3
        elif subscription.code == "BASIC":
            subscription.price = 10
            subscription.course_limit = 5
        else:
            subscription.price = 20
            subscription.course_limit = 7
    session.commit()

    op.alter_column("subscription", "price", nullable=False)
    op.alter_column("subscription", "course_limit", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'course_limit')
    op.drop_column('subscription', 'price')
    # ### end Alembic commands ###
