"""Subscriber table

Revision ID: d6c94e13f5e8
Revises: c2f14af701f9
Create Date: 2021-12-04 10:14:14.846804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c94e13f5e8'
down_revision = 'c2f14af701f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber',
    sa.Column('subscriber_id', sa.String(), nullable=False),
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('subscriber_id')
    )
    op.create_index(op.f('ix_subscriber_subscriber_id'), 'subscriber', ['subscriber_id'], unique=False)
    op.create_table('subscriber_suscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.String(), nullable=False),
    sa.Column('subscription_code', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('courses_limit', sa.Integer(), nullable=False),
    sa.Column('courses_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscriber.subscriber_id'], ),
    sa.ForeignKeyConstraint(['subscription_code'], ['subscription.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriber_suscription')
    op.drop_index(op.f('ix_subscriber_subscriber_id'), table_name='subscriber')
    op.drop_table('subscriber')
    # ### end Alembic commands ###
