"""Subscriptions accesses

Revision ID: f43ebc2e3e38
Revises: deecdbe7efc1
Create Date: 2021-11-26 20:13:07.235937

"""
import sqlalchemy as sa
from alembic import op
# revision identifiers, used by Alembic.
from sqlalchemy import column, table, String

revision = 'f43ebc2e3e38'
down_revision = 'deecdbe7efc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_accesses',
                    sa.Column('subscription_parent_code', sa.String(), nullable=False),
                    sa.Column('subscription_accessed_code', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['subscription_accessed_code'], ['subscription.code'], ),
                    sa.ForeignKeyConstraint(['subscription_parent_code'], ['subscription.code'], ),
                    sa.PrimaryKeyConstraint('subscription_parent_code', 'subscription_accessed_code')
                    )
    # ### end Alembic commands ###
    sub_table = table('subscription_accesses',
                      column('subscription_parent_code', String),
                      column('subscription_accessed_code', String),
                      )
    op.bulk_insert(sub_table, [
        {"subscription_parent_code": "BASIC", "subscription_accessed_code": "FREE"},
        {"subscription_parent_code": "FULL", "subscription_accessed_code": "FREE"},
        {"subscription_parent_code": "FULL", "subscription_accessed_code": "BASIC"},
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_accesses')
    # ### end Alembic commands ###
