name: ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_COURSES_TOKEN }}
      COV_OUTFILE: coverage.xml
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Linter
        run: |
          python -m flake8
      - name: Unit & Integration test
        run: |
          pip install pytest
          pip install pytest-cov
          pip install coveralls
          coverage run -m pytest test
          coverage report -m
          coverage xml -o ${{ env.COV_OUTFILE }}
          coveralls --submit=${{ env.COV_OUTFILE }}
